<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class DefaultExerciseSeeder extends Seeder
{
    public function run(): void
    {
        // Primero obtenemos los IDs de los grupos musculares
        $muscleGroups = DB::table('muscle_groups')->get()->keyBy('name');

        $exercises = [
            // PECHO (8 ejercicios)
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Press de banca plano',
                'description' => 'Ejercicio fundamental para el desarrollo del pecho. Tumbado en banco plano, bajar la barra hasta el pecho y empujar hacia arriba. Trabaja todo el pectoral con énfasis en la porción media.',
                'muscle_group_id' => $muscleGroups['Pecho (Pectorales)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Press de banca inclinado',
                'description' => 'Variante del press en banco inclinado (30-45 grados). Enfatiza el trabajo del pectoral superior. Excelente para desarrollar la porción clavicular del pectoral mayor.',
                'muscle_group_id' => $muscleGroups['Pecho (Pectorales)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Press de banca declinado',
                'description' => 'Press en banco declinado. Enfatiza la porción inferior del pectoral. Permite manejar más peso que las variantes plana e inclinada.',
                'muscle_group_id' => $muscleGroups['Pecho (Pectorales)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Fondos en paralelas',
                'description' => 'Ejercicio con peso corporal en barras paralelas. Inclinándose hacia adelante se enfatiza el pecho. Gran activación del pectoral inferior y tríceps.',
                'muscle_group_id' => $muscleGroups['Pecho (Pectorales)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Aperturas con mancuernas',
                'description' => 'Tumbado en banco, abrir los brazos en arco con mancuernas. Excelente ejercicio de aislamiento para estirar y contraer el pectoral. Enfoque en la técnica sobre el peso.',
                'muscle_group_id' => $muscleGroups['Pecho (Pectorales)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Cruces en polea alta',
                'description' => 'De pie entre dos poleas altas, cruzar los cables hacia abajo y adelante. Tensión constante en el pectoral durante todo el movimiento. Ideal para congestión muscular.',
                'muscle_group_id' => $muscleGroups['Pecho (Pectorales)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Press con mancuernas',
                'description' => 'Similar al press de banca pero con mancuernas. Mayor rango de movimiento y activación de músculos estabilizadores. Permite corregir desbalances entre lados.',
                'muscle_group_id' => $muscleGroups['Pecho (Pectorales)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Flexiones (Push-ups)',
                'description' => 'Ejercicio clásico con peso corporal. Versátil y funcional, se puede progresar con variantes (pies elevados, con lastre, explosivas). Excelente para fuerza relativa.',
                'muscle_group_id' => $muscleGroups['Pecho (Pectorales)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ESPALDA ALTA - TRAPECIO (4 ejercicios)
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Encogimientos con barra',
                'description' => 'De pie con barra, elevar los hombros hacia las orejas contrayendo el trapecio superior. Mantener brazos extendidos. Fundamental para desarrollo del trapecio.',
                'muscle_group_id' => $muscleGroups['Espalda alta (Trapecio)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Encogimientos con mancuernas',
                'description' => 'Variante con mancuernas que permite mayor rango de movimiento. Posición neutral de las manos reduce estrés en hombros. Excelente para corregir asimetrías.',
                'muscle_group_id' => $muscleGroups['Espalda alta (Trapecio)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Face pulls',
                'description' => 'En polea alta, tirar hacia la cara separando las manos. Trabaja trapecio medio, deltoides posterior y rotadores externos. Excelente para salud del hombro.',
                'muscle_group_id' => $muscleGroups['Espalda alta (Trapecio)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Remo alto con barra',
                'description' => 'De pie, tirar la barra hacia arriba cerca del cuerpo hasta la altura del pecho. Trabaja trapecio superior y deltoides lateral. Mantener codos por encima de las manos.',
                'muscle_group_id' => $muscleGroups['Espalda alta (Trapecio)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ESPALDA MEDIA - ROMBOIDES (3 ejercicios)
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Remo con barra',
                'description' => 'Inclinado hacia adelante, tirar la barra hacia el abdomen. Ejercicio compuesto fundamental para espalda media. Mantener espalda recta y apretar escápulas al final.',
                'muscle_group_id' => $muscleGroups['Espalda media (Romboides)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Remo con mancuerna a una mano',
                'description' => 'Apoyado en banco, remar con una mancuerna. Permite gran rango de movimiento y concentración unilateral. Excelente para corregir desbalances musculares.',
                'muscle_group_id' => $muscleGroups['Espalda media (Romboides)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Remo en polea baja',
                'description' => 'Sentado, tirar del cable hacia el abdomen. Tensión constante durante todo el recorrido. Mantener pecho elevado y apretar escápulas en la contracción.',
                'muscle_group_id' => $muscleGroups['Espalda media (Romboides)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // DORSALES (5 ejercicios)
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Dominadas',
                'description' => 'Ejercicio rey para dorsales. Colgado de barra, elevar el cuerpo hasta barbilla sobre barra. Agarre prono enfatiza dorsales. Desarrolla fuerza relativa excepcional.',
                'muscle_group_id' => $muscleGroups['Dorsales (Dorsal ancho)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Jalón al pecho',
                'description' => 'Sentado en máquina, tirar barra hacia el pecho. Alternativa a dominadas para construir fuerza. Permite trabajar con diferentes agarres y ángulos.',
                'muscle_group_id' => $muscleGroups['Dorsales (Dorsal ancho)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Peso muerto',
                'description' => 'Ejercicio fundamental de fuerza. Levantar barra desde el suelo manteniendo espalda recta. Trabaja toda la cadena posterior incluyendo dorsales, erectores y glúteos.',
                'muscle_group_id' => $muscleGroups['Dorsales (Dorsal ancho)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Pull-over con mancuerna',
                'description' => 'Tumbado en banco, pasar mancuerna desde detrás de la cabeza hasta sobre el pecho. Excelente para expandir caja torácica y estirar dorsales.',
                'muscle_group_id' => $muscleGroups['Dorsales (Dorsal ancho)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Remo en máquina',
                'description' => 'Remo sentado en máquina con agarre neutral. Estabilización asistida permite enfocarse en la contracción del dorsal. Ideal para series de alto volumen.',
                'muscle_group_id' => $muscleGroups['Dorsales (Dorsal ancho)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // DELTOIDES ANTERIOR (3 ejercicios)
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Press militar con barra',
                'description' => 'De pie o sentado, empujar barra desde hombros hasta extensión completa. Ejercicio fundamental para desarrollo de hombros. Trabaja principalmente deltoides anterior y lateral.',
                'muscle_group_id' => $muscleGroups['Hombros - Deltoides anterior']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Press con mancuernas sentado',
                'description' => 'Sentado, empujar mancuernas desde hombros. Mayor rango de movimiento que con barra. Permite identificar y corregir desbalances entre hombros.',
                'muscle_group_id' => $muscleGroups['Hombros - Deltoides anterior']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Elevaciones frontales',
                'description' => 'De pie, elevar mancuernas o barra al frente hasta altura de hombros. Ejercicio de aislamiento para deltoides anterior. Controlar el movimiento evitando impulso.',
                'muscle_group_id' => $muscleGroups['Hombros - Deltoides anterior']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // DELTOIDES LATERAL (2 ejercicios)
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Elevaciones laterales con mancuernas',
                'description' => 'De pie, elevar mancuernas a los lados hasta altura de hombros. Ejercicio clave para amplitud de hombros. Mantener codos ligeramente flexionados y controlar el descenso.',
                'muscle_group_id' => $muscleGroups['Hombros - Deltoides lateral']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Elevaciones laterales en polea',
                'description' => 'Elevaciones laterales usando polea baja. Tensión constante durante todo el recorrido. Permite trabajar con diferentes ángulos y enfatizar la contracción.',
                'muscle_group_id' => $muscleGroups['Hombros - Deltoides lateral']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // DELTOIDES POSTERIOR (2 ejercicios)
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Pájaros con mancuernas',
                'description' => 'Inclinado hacia adelante, abrir brazos en arco con mancuernas. Fundamental para deltoides posterior. Crucial para balance muscular y salud del hombro.',
                'muscle_group_id' => $muscleGroups['Hombros - Deltoides posterior']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Pájaros en máquina pec deck',
                'description' => 'Sentado de frente a la máquina, separar los brazos. Aislamiento puro del deltoides posterior. Estabilización asistida permite enfocarse en la contracción muscular.',
                'muscle_group_id' => $muscleGroups['Hombros - Deltoides posterior']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // BÍCEPS (6 ejercicios)
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Curl con barra',
                'description' => 'De pie, flexionar codos elevando barra. Ejercicio básico para masa de bíceps. Mantener codos fijos y controlar el movimiento sin balancear el cuerpo.',
                'muscle_group_id' => $muscleGroups['Bíceps']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Curl con mancuernas',
                'description' => 'Flexión de codos con mancuernas. Permite supinación durante el movimiento para mayor contracción del bíceps. Posibilita trabajo unilateral y corrección de asimetrías.',
                'muscle_group_id' => $muscleGroups['Bíceps']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Curl martillo',
                'description' => 'Curl con agarre neutral (palmas enfrentadas). Trabaja bíceps y braquial anterior. Fundamental para grosor del brazo y fuerza de agarre.',
                'muscle_group_id' => $muscleGroups['Bíceps']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Curl en banco Scott',
                'description' => 'Brazos apoyados en banco inclinado, elimina impulso. Aislamiento puro del bíceps. Excelente para trabajar el pico del bíceps.',
                'muscle_group_id' => $muscleGroups['Bíceps']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Curl concentrado',
                'description' => 'Sentado, codo apoyado en muslo interno. Máximo aislamiento del bíceps. Permite concentración total en la contracción muscular.',
                'muscle_group_id' => $muscleGroups['Bíceps']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Curl en polea',
                'description' => 'Curl usando polea baja. Tensión constante durante todo el recorrido. Permite diferentes agarres y ángulos para variedad de estímulo.',
                'muscle_group_id' => $muscleGroups['Bíceps']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // TRÍCEPS (6 ejercicios)
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Press de banca agarre cerrado',
                'description' => 'Press con manos a anchura de hombros. Ejercicio compuesto fundamental para tríceps. Permite manejar cargas pesadas para desarrollo de fuerza y masa.',
                'muscle_group_id' => $muscleGroups['Tríceps']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Fondos en paralelas para tríceps',
                'description' => 'Fondos manteniendo torso vertical. Excelente ejercicio con peso corporal. Trabaja principalmente las tres cabezas del tríceps.',
                'muscle_group_id' => $muscleGroups['Tríceps']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Extensiones en polea alta',
                'description' => 'De pie frente a polea alta, extender codos empujando hacia abajo. Aislamiento clásico de tríceps. Mantener codos fijos y controlar el retorno.',
                'muscle_group_id' => $muscleGroups['Tríceps']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Extensiones con mancuerna tras nuca',
                'description' => 'Sentado o de pie, extender mancuerna desde detrás de la cabeza. Enfatiza la cabeza larga del tríceps. Excelente para desarrollo completo del brazo.',
                'muscle_group_id' => $muscleGroups['Tríceps']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Patada de tríceps',
                'description' => 'Inclinado, extender mancuerna hacia atrás. Aislamiento con énfasis en la contracción pico. Mantener brazo superior paralelo al suelo.',
                'muscle_group_id' => $muscleGroups['Tríceps']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Press francés',
                'description' => 'Tumbado, bajar barra hacia frente flexionando solo codos. Ejercicio clásico para masa de tríceps. Mantener brazos superiores fijos durante todo el movimiento.',
                'muscle_group_id' => $muscleGroups['Tríceps']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ANTEBRAZOS (3 ejercicios)
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Curl de muñeca con barra',
                'description' => 'Antebrazos apoyados, flexionar muñecas con barra. Desarrollo de flexores del antebrazo. Fundamental para fuerza de agarre.',
                'muscle_group_id' => $muscleGroups['Antebrazos']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Curl de muñeca inverso',
                'description' => 'Similar al anterior pero con palmas hacia abajo. Trabaja extensores del antebrazo. Importante para balance muscular y prevención de lesiones.',
                'muscle_group_id' => $muscleGroups['Antebrazos']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Farmer\'s walk',
                'description' => 'Caminar sosteniendo pesas pesadas a los lados. Ejercicio funcional que desarrolla fuerza de agarre excepcional. Trabaja antebrazos, trapecios y core.',
                'muscle_group_id' => $muscleGroups['Antebrazos']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ABDOMINALES (5 ejercicios)
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Crunch abdominal',
                'description' => 'Tumbado boca arriba, elevar parte superior del torso. Ejercicio básico para recto abdominal. Evitar tirar del cuello, el movimiento viene del abdomen.',
                'muscle_group_id' => $muscleGroups['Abdominales (Recto abdominal)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Elevación de piernas',
                'description' => 'Tumbado o colgado, elevar piernas hacia el pecho. Trabaja porción inferior del recto abdominal. Mantener lumbar pegada al suelo en versión tumbada.',
                'muscle_group_id' => $muscleGroups['Abdominales (Recto abdominal)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Plancha abdominal',
                'description' => 'Mantener posición de tabla apoyado en antebrazos. Ejercicio isométrico fundamental para core. Mantener cuerpo recto sin hundir cadera.',
                'muscle_group_id' => $muscleGroups['Abdominales (Recto abdominal)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Abdominales en polea',
                'description' => 'Arrodillado frente a polea alta, flexionar torso hacia abajo. Permite progresión de carga fácilmente. Excelente para desarrollo de fuerza abdominal.',
                'muscle_group_id' => $muscleGroups['Abdominales (Recto abdominal)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Mountain climbers',
                'description' => 'En posición de plancha, alternar llevando rodillas al pecho. Ejercicio dinámico que combina core y cardio. Mantener cadera baja y movimiento controlado.',
                'muscle_group_id' => $muscleGroups['Abdominales (Recto abdominal)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // OBLICUOS (3 ejercicios)
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Russian twist',
                'description' => 'Sentado con pies elevados, rotar torso de lado a lado. Trabaja oblicuos y recto abdominal. Puede añadirse peso para progresión.',
                'muscle_group_id' => $muscleGroups['Oblicuos']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Plancha lateral',
                'description' => 'Apoyado lateralmente en un antebrazo, mantener cuerpo recto. Isométrico específico para oblicuos. Fundamental para estabilidad lateral del core.',
                'muscle_group_id' => $muscleGroups['Oblicuos']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Flexiones laterales con mancuerna',
                'description' => 'De pie, flexionar lateralmente el torso sosteniendo mancuerna. Trabaja oblicuos en estiramiento y contracción. Controlar el movimiento evitando balanceo.',
                'muscle_group_id' => $muscleGroups['Oblicuos']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // CUÁDRICEPS (5 ejercicios)
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Sentadilla con barra',
                'description' => 'Ejercicio rey para piernas. Barra en espalda alta, descender hasta muslos paralelos o más. Desarrolla fuerza, masa y potencia en todo el tren inferior.',
                'muscle_group_id' => $muscleGroups['Cuádriceps']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Prensa de piernas',
                'description' => 'Empujar plataforma con pies. Permite manejar cargas muy pesadas con menor demanda técnica. Excelente para volumen en cuádriceps.',
                'muscle_group_id' => $muscleGroups['Cuádriceps']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Zancadas con mancuernas',
                'description' => 'Dar paso largo y descender flexionando ambas rodillas. Ejercicio unilateral que mejora balance y corrige asimetrías. Funcional y versátil.',
                'muscle_group_id' => $muscleGroups['Cuádriceps']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Extensión de cuádriceps en máquina',
                'description' => 'Sentado, extender piernas contra resistencia. Aislamiento puro de cuádriceps. Excelente para pre-fatiga o trabajo final de congestión.',
                'muscle_group_id' => $muscleGroups['Cuádriceps']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Sentadilla búlgara',
                'description' => 'Pie trasero elevado en banco, descender con pierna delantera. Variante unilateral intensa. Excelente para desarrollo de cuádriceps y glúteos.',
                'muscle_group_id' => $muscleGroups['Cuádriceps']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ISQUIOTIBIALES (3 ejercicios)
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Peso muerto rumano',
                'description' => 'Variante de peso muerto con piernas casi extendidas. Enfatiza isquiotibiales y glúteos. Fundamental para desarrollo de cadena posterior.',
                'muscle_group_id' => $muscleGroups['Isquiotibiales']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Curl femoral tumbado',
                'description' => 'Tumbado boca abajo, flexionar piernas contra resistencia. Aislamiento directo de isquiotibiales. Permite trabajo unilateral o bilateral.',
                'muscle_group_id' => $muscleGroups['Isquiotibiales']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Curl femoral sentado',
                'description' => 'Sentado, flexionar piernas contra resistencia. Variante del curl que permite mayor rango de movimiento. Excelente para desarrollo completo de isquiotibiales.',
                'muscle_group_id' => $muscleGroups['Isquiotibiales']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // GLÚTEOS (2 ejercicios)
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Hip thrust',
                'description' => 'Espalda apoyada en banco, empujar cadera hacia arriba con barra. Ejercicio más efectivo para glúteos. Permite cargas muy pesadas con mínimo estrés lumbar.',
                'muscle_group_id' => $muscleGroups['Glúteos']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Patada de glúteo en polea',
                'description' => 'De pie frente a polea baja, extender pierna hacia atrás. Aislamiento de glúteo mayor. Permite enfocarse en la contracción pico.',
                'muscle_group_id' => $muscleGroups['Glúteos']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // GEMELOS (2 ejercicios)
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Elevación de talones de pie',
                'description' => 'De pie con peso en hombros, elevar talones. Enfatiza gastrocnemio. Fundamental para desarrollo de pantorrillas. Buscar rango completo de movimiento.',
                'muscle_group_id' => $muscleGroups['Gemelos (Pantorrillas)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Elevación de talones sentado',
                'description' => 'Sentado con peso en rodillas, elevar talones. Enfatiza sóleo. Complementa el trabajo de pie para desarrollo completo de gemelos.',
                'muscle_group_id' => $muscleGroups['Gemelos (Pantorrillas)']->id,
                'trainer_id' => null,
                'is_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('exercises')->insert($exercises);
    }
}
